### ISSUE TITLE
many error in node

### ISSUE THREAD

**Issue by runvirus** [stephenfewer/grinder#69]
how can i fix this error 

        By Stephen Fewer of Harmony Security (www.harmonysecurity.com)
                                             GRINDER - Version 0.7-Dev

[+G+] Starting at 2016-11-07 21:23:08
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
: 1114: A dynamic link library (DLL) initialization routine failed.   - C:/node/
lib/metasm/metasm/dynldr-windows-x64-19.so (LoadError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/node/lib/metasm/metasm/dynldr.rb:612:in `start'
        from C:/node/lib/metasm/metasm/dynldr.rb:1297:in `<class:DynLdr>'
        from C:/node/lib/metasm/metasm/dynldr.rb:11:in `<module:Metasm>'
        from C:/node/lib/metasm/metasm/dynldr.rb:10:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/node/lib/metasm/metasm/os/windows.rb:8:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/node/core/configuration.rb:38:in `config_init'
        from C:/node/grinder.rb:148:in `run'
        from C:/node/grinder.rb:269:in `<main>'

C:\node>

**Comment by maycon-zz** [comment]
Try using `Ruby 2.0` instead `Ruby 2.3`.

**Comment by littleshadoow** [comment]
Hello, 
I'm using ruby 2.0 ​​but I have a similar problem:

```
Starting at 2017-07-21 02:46:15
grinder.rb:228:in `wait'C:/grinder/node/lib/metasm/metasm/parse_c.rb:2979:in `[]: 'Interrup: tInterrup
t       from grinder.rb:228:in `run'

        from grinder.rb:269:in `<main>' from C:/grinder/node/lib/metasm/metasm/parse_c.rb:3118:in `block in to_array'

./core/server.rb:292:in `join'  from C:/grinder/node/lib/metasm/metasm/parse_c.rb:3118:in `times':
Interrup        from C:/grinder/node/lib/metasm/metasm/parse_c.rb:3118:in `to_array'

        from C:/grinder/node/lib/metasm/metasm/parse_c.rb:3124:in `to_strz'C:\grinder\node>
t       from C:/grinder/node/lib/metasm/metasm/os/windows.rb:1538:in `block in list_modules'

        from C:/grinder/node/lib/metasm/metasm/os/windows.rb:1534:in `loop'     from ./core/server.rb:292:in `wait'

        from C:/grinder/node/lib/metasm/metasm/os/windows.rb:1534:in `list_modules'     from ./core/server.rb:352:in `<main>'

        from C:/grinder/node/lib/metasm/metasm/os/windows.rb:1254:in `modules'
        from C:/grinder/node/core/debug/debugger.rb:770:in `block in main'
        from C:/grinder/node/core/debug/debugger.rb:769:in `each'
        from C:/grinder/node/core/debug/debugger.rb:769:in `main'
        from ./browser/internetexplorer.rb:308:in `<main>'
```
