### ISSUE TITLE
Metasm is not working on 64 bit machine -Ruby 2.5 x64 installed

### ISSUE THREAD

**Issue by bikashdash** [stephenfewer/grinder#74]
While i was trying to install the grinder i got the following error

C:\Grinder\node>ruby grinder.rb
Traceback (most recent call last):
        5: from grinder.rb:9:in `<main>'
        4: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        3: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        2: from C:/Grinder/node/core/configuration.rb:6:in `<top (required)>'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- lib/metasm/metasm (LoadError)
Metasm working as below

C:\Grinder\node>ruby -r metasm -e 'p Metasm::VERSION'
1

**Comment by bikashdash** [comment]
@stephenfewer  Any idea what might be the reason ?
